StarTEDWeb/Pages/Employees.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StarTEDsystem.BLL;
using StarTEDsystem.Entities;
using StarTEDWeb.Helpers;

namespace StarTEDWeb.Pages
{
    public class EmployeesModel : PageModel
    {
        #region Define a CategoryServices field and initialize it using constructor injection
        private readonly ClubServices _clubServices;
        private readonly EmployeeServices _employeeServices;
        public EmployeesModel(ClubServices clubServices, EmployeeServices employeeServices)
        {
            _clubServices = clubServices;
            _employeeServices = employeeServices;
        }
        #endregion

        #region Define properties for data access by the page
        [TempData]
        public string FeedbackMessage { get; set; }

        public List<Club> CategoryList { get; set; } = new();
        public List<Employee> EmployeeIDList { get; private set; } = new();
        #endregion

        #region Define code that gets executed when the page is accessed using a HTTP GET request
        [BindProperty(SupportsGet = true)]
        public bool selectedRadioButton { get; set; } = true;

        #region Paginator
        private const int PAGE_SIZE = 5;

        public Paginator Pager { get; set; }
        #endregion
        public void OnGet(int? currentPage)
        {
            {
                int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                PageState current = new(pagenumber, PAGE_SIZE);
                int totalcount;

                CategoryList = _clubServices.Club_List(selectedRadioButton, PAGE_SIZE, pagenumber, out totalcount);
                EmployeeIDList = _employeeServices.employee_byID();

                Pager = new Paginator(totalcount, current);

                FeedbackMessage = $"Search returned {CategoryList.Count} result(s).";
                


            }
        }
        #endregion
    
        public IActionResult OnPostList()
        {
            return RedirectToPage(new { selectedRadioButton = selectedRadioButton });
        }







    }
}

StarTEDWeb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace StarTEDWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

StarTEDWeb/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StarTEDWeb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

StarTEDWeb/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StarTEDWeb.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

StarTEDWeb/Pages/clubs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StarTEDsystem.BLL;
using StarTEDsystem.Entities;

namespace StarTEDWeb.Pages
{
    public class ClubsModel : PageModel
    {
        #region Define a CategoryServices field and initialize it using constructor injection
        private readonly ClubServices _clubServices;
        public ClubsModel(ClubServices clubServices)
        {
            _clubServices = clubServices;
        }
        #endregion

        #region Define properties for data access by the page
        [TempData]
        public string FeedbackMessage { get; set; }

        public List<Club> CategoryList { get; set; } = new();
        #endregion

        #region Define code that gets executed when the page is accessed using a HTTP GET request
        public void OnGet()
        {
            // Fetch a list of category from the database using our BLL object
/*            CategoryList = _clubServices.Club_List();
*/        }
        #endregion

        public IActionResult Edit(bool active)
        {
            return RedirectToPage();
        }

    }
}

StarTEDWeb/Pages/Employees.cshtml
@page "{selectedRadioButton?}"
@model StarTEDWeb.Pages.EmployeesModel
@{
    ViewData["Title"] = "Employee List";
}
<h1>Clubs By Status</h1>

<p>@Model.FeedbackMessage</p>

<form method="post">
    <p>Select Club Status:</p>
  <input type="radio" asp-for="@Model.selectedRadioButton" value="true" />Active
  <input type="radio" asp-for="@Model.selectedRadioButton" value="false" />In-Active<br/>
  
  <button type="submit" asp-page-handler="List">Search</button>

@if(Model.CategoryList.Count > 0)
{
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Staff</th>
                <th>Fee</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model.CategoryList)
            {
                <tr>
                    <td>
                        <a asp-page="/Clubs">Edit</a> 
                    </td>
                    <td>@item.ClubID</td>
                    <td>@item.ClubName</td>
                    <td>
                        <select>
                            @foreach(var currentEmployee in @Model.EmployeeIDList)
                                    {
                                    if (item.EmployeeID != null)
                                    {
                                        <option value="@currentEmployee.EmployeeID"
                                            selected=@(currentEmployee.EmployeeID == item.EmployeeID)>
                                            @currentEmployee.FullName
                                        </option>
                                    }
                                    
                                    }
                                <option>No Staff Member</option>
                        </select>
                    </td>
                    <td>@item.Fee.ToString("0.00")</td>
                </tr>
            }
        </tbody>

        <tfoot>
                    <tr>
                        <td colspan="3">
                            @{
                                foreach(var pageRef in Model.Pager)
                                {
                                    if (pageRef == Model.Pager.CurrentPage)
                                    {
                                        <b>@pageRef.Text</b>
                                    }
                                    else
                                    {                       
                                        <a title="Page @pageRef.Page"
                                           asp-page="/Employees"
                                           asp-route-currentpage="@pageRef.Page"
                                           asp-route-ProductNameSearchValue="@Model.selectedRadioButton">
                                            @pageRef.Text   
                                         </a>
                                    }
                                }
                            }
                        </td>
                    </tr>
                </tfoot>

    </table>    
}

</form>

StarTEDWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to CPSC1517 StarTED</h1>
    <h2> Project Section: A02</h2>
    <br />
    <h3>Deliverable Descriptions</h3>
    <p>Query: Display the results of looking up Clubs by their active status (active/non-active). The employee drop-down has only employees active with clubs. Follow the mock-up below as a guide to displaying the results. Remember to include pagination.
    Each club line will contain a link to allow for record maintenance. This link will cause your CRUD page to appear. Add a separate New button to have your CRUD appear.</p>
    <p>CRUD: Single Item Create/Read/Update/Deactivate (Delete) <br />
        Note the following: <br />
    Club entries are not deleted. Rather than providing a "delete" button, inlude a "Deactivate" button and in the BLL method, change the Active flag to false and update the database for that entry.
    For entering the employee id of available staff, use an "input with a "datalist. The datalist is based the results of a query returning only employees who are instructors, office administrator or technical support.</p>
</div>

StarTEDWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StarTEDWeb - </title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StarTEDWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">StarTEDWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Employees">Query</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Clubs">Crud</a>
                        </li>
               
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StarTEDWeb - By Ricard Dong -<a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StarTEDWeb/Pages/clubs.cshtml
@page
@model StarTEDWeb.Pages.ClubsModel
@{
    ViewData["Title"] = "Update Club Status";
}
<p>@Model.FeedbackMessage</p>

<h1>Edit @Model.CategoryList</h1>  

<form asp-action="Edit" method="post"> 
   <div> 
      @*<label asp-for = ""></label> 
      <input asp-for = "" /> 
      <span asp-validation-for = ""></span> *@
   </div> 
   
   <div> 
      <input type = "submit" value = "Save" /> 
   </div> 
</form>
}